apiVersion: v1
kind: Service
metadata:
  labels:
    app: minecraft-server
  name: minecraft-server
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 25565
    targetPort: 25565
  selector:
    app: minecraft-server
